# Generated by Django 5.1.5 on 2025-02-08 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='allowed_ips',
        ),
    ]
