# Generated by Django 5.1.5 on 2025-02-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_remove_customuser_allowed_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
