# Generated by Django 5.1.6 on 2025-02-26 22:00

from django.db import migrations

def populate_created_by(apps, schema_editor):
    # Get the historical model
    Transaction = apps.get_model('auth_system', 'Transaction')
    
    # Update all existing transactions with a default admin username
    Transaction.objects.filter(created_by__isnull=True).update(created_by='admin')

def reverse_populate_created_by(apps, schema_editor):
    # This is a reversible migration, so we can set created_by back to null
    Transaction = apps.get_model('auth_system', 'Transaction')
    Transaction.objects.all().update(created_by=None)

class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_transaction_created_by'),
    ]

    operations = [
        migrations.RunPython(populate_created_by, reverse_populate_created_by),
    ]
