# Generated by Django 5.1.6 on 2025-03-01 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_populate_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
    ]
