# Generated by Django 5.1.5 on 2025-02-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_customuser_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='verified_email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verified_phone',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='pallalarakesh5@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='+918008562381', max_length=15),
        ),
    ]
