# Generated by Django 5.1.6 on 2025-03-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_remove_transaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='google_auth_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin_2fa_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
