# Generated by Django 5.1.6 on 2025-02-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_transaction_amount_paid_transaction_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('upi', 'UPI')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
