# Generated by Django 5.1.6 on 2025-03-03 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0005_customuser_google_auth_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_type', models.CharField(max_length=100)),
                ('original_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('weight_loss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('processed_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('processing_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('original_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_stocks', to='auth_system.customer')),
            ],
            options={
                'db_table': 'processed_stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
