# Generated by Django 5.1.6 on 2025-02-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0006_transaction_notes_transaction_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='mohanvarma1022@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='+916281287188', max_length=15),
        ),
    ]
