# Generated by Django 5.1.6 on 2025-03-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0007_inventory_inventoryexpense_delete_processedstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryexpense',
            name='new_avg_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryexpense',
            name='new_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryexpense',
            name='old_avg_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryexpense',
            name='old_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
