# Generated by Django 5.1.6 on 2025-02-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0008_alter_customer_options_customer_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
