# Generated by Django 5.1.6 on 2025-03-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0008_inventoryexpense_new_avg_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryexpense',
            name='is_processing',
            field=models.BooleanField(default=False, help_text='Flag to indicate if this expense is related to processing'),
        ),
    ]
