# Generated by Django 5.1.6 on 2025-03-05 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0008_clear_inventory_data'),
        ('auth_system', '0009_inventoryexpense_is_processing'),
    ]

    operations = [
    ]
