# Generated by Django 5.1.6 on 2025-03-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0010_merge_20250305_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryexpense',
            name='expenditure',
        ),
        migrations.RemoveField(
            model_name='inventoryexpense',
            name='weight_loss',
        ),
    ]
