# Generated by Django 5.1.6 on 2025-03-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0011_remove_inventoryexpense_expenditure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryexpense',
            name='expenditure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryexpense',
            name='weight_loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventoryexpense',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryexpense',
            name='is_processing',
            field=models.BooleanField(default=False),
        ),
    ]
